---
- name: Ensure the data directory exists
  ansible.builtin.file:
    path: "{{ kibana_data_dir }}"
    state: directory
    owner: root
    group: docker
    mode: "0777"

- name: Pull specified Kibana docker image
  community.docker.docker_image:
    name: "{{ kibana_image }}"
    source: pull
    tag: "{{ kibana_version }}"
  notify: Remove Kibana

- name: Ensure all handlers run before continuing
  ansible.builtin.meta: flush_handlers

- name: Copy Kibana configuration file
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: "{{ kibana_data_dir }}/kibana.yml"
    owner: root
    group: docker
    mode: "0644"
  notify: Restart Kibana

- name: Build environment variables for container
  ansible.builtin.set_fact:
    kibana_env: "{{ (kibana_env | combine(item.env)) if item.apply else kibana_env }}"
  loop: "{{ kibana_config }}"

- name: Ensure Kibana container is created
  community.docker.docker_container:
    container_default_behavior: no_defaults
    detach: true
    env: "{{ kibana_env }}"
    image: "{{ kibana_image }}:{{ kibana_version }}"
    interactive: false
    name: "{{ kibana_name }}"
    ports: "{{ ((kibana_port | string) + ':5601') if kibana_expose else '[]' }}"
    pull: false
    restart_policy: always
    state: present
    volumes:
      - "{{ kibana_data_dir }}:/usr/share/kibana/config"
  notify: Restart Kibana
