---
- name: Restart Kibana
  command: "docker restart {{ item }}"
  with_items:
    - "{{ kibana_name }}"

- name: Remove Kibana
  command: "docker stop {{ item }} && docker rm {{ item }}"
  register: results
  with_items:
    - "{{ kibana_name }}"
  failed_when: >-
    results is failed and
    "No such container" not in results.stderr | default(false)
